
# This file was *autogenerated* from the file exp.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_9 = Integer(9); _sage_const_20 = Integer(20); _sage_const_50 = Integer(50)
def fact(n):
	"""
	Returns factorial of ``n``.
	"""
	if n==_sage_const_0 :
		return _sage_const_1 
	else:
		return n*fact(n-_sage_const_1 )

def expr(x,i):
	"""
	Returns ``i``th term of ``exp(x)``.
	"""
	return x**i/fact(i)

__tmp__=var("x"); f = symbolic_expression(sum([expr(x,i) for i in range(_sage_const_9 )])).function(x)

a = animate([plot(sum([expr(x, j) for j in range(i)]), xmin=-_sage_const_3 , xmax=_sage_const_3 , ymin=-_sage_const_2 , ymax=_sage_const_20 ) for i in range(_sage_const_9 )])

a.show(delay=_sage_const_50 )

