
# This file was *autogenerated* from the file pascal.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_32 = Integer(32)
class colors:
	"""
	Class initialising unicode for various colors.
	"""
	W  = '\033[0m'  # white (normal)
	R  = '\033[31m' # red
	B  = '\033[34m' # blue

def print_pascal(N):
	"""
	Prints pascal triangle with odd in red and even in blue.
	"""
	a = [[binomial(n,i) for i in range(n+_sage_const_1 )] for n in range(N)]
	for i in range(N):
		s = "   "*(n-i)
		for j in range(_sage_const_0 ,i+_sage_const_1 ):
			if a[i][j]%_sage_const_2  == _sage_const_0 :
				s += colors.B+'{0:10}'.format(a[i][j])+colors.W
			else:
				s += colors.R+'{0:10}'.format(a[i][j])+colors.W
		print s

print_pascal(_sage_const_32 )

